[versions]
kotlin = "2.3.0"
kotlin-wrappers = "1.0.0-pre.754"
jgit = "7.5.0.202512021534-r"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit"}
